title: Bicrement
name: Bicrement
subtitle: Where (Progress++)++
url: http://www.bicrement.com
description: Bicrement is about anything I am interested. I write to make self (progress++)++.
author: Wang Zhuochun
author_abbr: Zhuochun
author_description:
page:
    home: /
    blog: /blog/
    about: /about/
    project: /project/
social:
    github: https://github.com/zhuochun
    linkedin: http://www.linkedin.com/in/zhuochun
    stackoverflow: http://stackoverflow.com/users/889972/mifeng
    twitter: https://twitter.com/zhuochun
    flickr: http://www.flickr.com/photos/mifeng
pygments: true
exclude: ['CNAME', 'README.md', '_drafts']
