# Site Settings
title: Bicrement
name: Bicrement
subtitle: "Where (Progress++)++"
description: "Bicrement is about making (progress++)++."
baseurl: ""
url: "http://www.bicrement.com"
email: zhuochun@hotmail.com

# Author
author: "Wang Zhuochun"
author_abbr: Zhuochun
author_description: ""

# Pages
page:
    home: /
    blog: /blog/
    note: /note/
    about: /about/
    project: /project/
social:
    github: https://github.com/zhuochun
    linkedin: http://www.linkedin.com/in/zhuochun
    stackoverflow: http://stackoverflow.com/users/889972/mifeng
    twitter: https://twitter.com/zhuochun
    flickr: http://www.flickr.com/photos/mifeng

# Build Settings
highlighter: pygments
markdown: kramdown
exclude: ['CNAME', 'README.md', '_drafts']
