# Site Settings
title: Bicrement
name: Bicrement
subtitle: "Where (Progress++)++"
description: "Bicrement contains a learner's writing."
baseurl: ""
url: "https://www.bicrement.com"
permalink: "/articles/:year/:title.html"

# Author
author: "Wang Zhuochun"
author_abbr: Zhuochun
author_email: zhuochun@hotmail.com
author_description: ""

# Pages
page:
    home: /
    blog: /blog/
    note: /note/
    about: /about/
    project: /project/
social:
    github: https://github.com/zhuochun
    linkedin: https://www.linkedin.com/in/zhuochun
    stackoverflow: https://stackoverflow.com/users/889972/mifeng
    twitter: https://twitter.com/zhuochun
    substack: https://bicrement.substack.com/
    flickr: https://www.flickr.com/photos/mifeng

# Build Settings
markdown: kramdown
encoding: UTF-8
highlighter: rouge
# Support Github Flavored Markdown
# http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  hard_wrap: false
# https://help.github.com/en/articles/configuring-jekyll
gfm_quirks: paragraph_end
# Exclude files
exclude: ['Gemfile', 'Gemfile.lock', 'CNAME', 'README.md', '_drafts']
